feat: analyse statique variable (#19)
* ajout de warning doubleDeclaration mais underfined reference

* fix undefined reference to

* fix std::cast error

* fix missing declaration of variable

* fix doubleDeclaration est une erreur

* affichage + correction condition

* increment error count

* ajout ligne + colonne de l'erreur

* ajout des classes unusedvariable et undeclaredvariable

* maj noms de classe

* ajout vérification unused variable - sdd moche

* detection d'une variable non definie dans le cas d'une expression

* ajout de tests pour les vérifications statiques

* ajout de commentaires assembleurs sur les analyses statiques

* fix character for comments in assembly

* ajout pragama once

* fix merge, compilation ok